services:
  redis:
    image: redis:latest
    container_name: container_redis
    ports:
      - "6379:6379"
    environment:
      - CONTAINER_PORT=6379
      - HOST_PORT=6379
    restart: unless-stopped
  
  backend:
    build:
      context: ./backend
    ports:
      - "7861:7861"
    container_name: container_backend
    environment:
      - CONTAINER_PORT=7861
      - HOST_PORT=7861
    volumes:
      - ./backend:/usr/src/app
      - /var/run/docker.sock:/var/run/docker.sock
      - /models:/models
    depends_on:
      - redis
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    ports:
      - "7860:7860"
    container_name: container_frontend
    depends_on:
      - backend
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
      - CONTAINER_PORT=7860
      - HOST_PORT=7860
    volumes:
      - ./frontend:/usr/src/app
      - /models:/models
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    restart: unless-stopped

  vllm:
    build:
      context: ./vllm
    image: xoo4foo/vllm3:latest
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "1370:1370"
    container_name: container_vllm
    volumes:
      - ./vllm/logs:/var/log
      - ./models:/models
    shm_size: 8gb
    environment:
      - NCCL_DEBUG=INFO
      - CONTAINER_PORT=1370